# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ard',
            fields=[
                ('ardid', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edevice',
            fields=[
                ('edeviceid', models.TextField(primary_key=True, serialize=False)),
                ('pin', models.IntegerField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('state', models.IntegerField()),
                ('pstates', models.TextField()),
                ('ardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Ard')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edeviceid', models.TextField()),
                ('previous_state', models.IntegerField()),
                ('state', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDet',
            fields=[
                ('deviceid', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('name', models.TextField()),
                ('deviceid', models.TextField(primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField()),
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rasp',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.User'),
        ),
        migrations.AddField(
            model_name='logindet',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.User'),
        ),
        migrations.AddField(
            model_name='ard',
            name='rasp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Rasp'),
        ),
    ]
