# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edevice',
            fields=[
                ('edeviceid', models.TextField(primary_key=True, serialize=False)),
                ('ardid', models.TextField()),
                ('pin', models.IntegerField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('state', models.IntegerField()),
                ('pstates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edeviceid', models.TextField()),
                ('previous_state', models.IntegerField()),
                ('state', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
