# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ard',
            fields=[
                ('ardid', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDet',
            fields=[
                ('deviceid', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('name', models.TextField()),
                ('deviceid', models.TextField(primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField()),
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rasp',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.User'),
        ),
        migrations.AddField(
            model_name='logindet',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.User'),
        ),
        migrations.AddField(
            model_name='ard',
            name='rasp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Rasp'),
        ),
    ]
