# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20171108_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edevice',
            name='ardid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Ard'),
        ),
    ]
